language: python
matrix:
  include:
  - python: 2.7
    PARALLELIZE=false
  - python: 3.5
    PARALLELIZE=false
  - python: 3.6
    PARALLELIZE=true
  - python: 3.7
    PARALLELIZE=false
    dist: xenial
  - python: 3.7
    PARALLELIZE=true
    dist: xenial
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
script: pytest # run tests
after_success: